"""
EPL JavaScript Transpiler (v2.0)
Converts EPL AST to JavaScript for client-side web execution
and Node.js target. Supports: variables, functions, loops, conditions,
classes, string/list methods, DOM helpers, async/await, modules,
super calls, proper constructor mapping, and target-aware output.
"""

import re

from epl import ast_nodes as ast


class JSTranspiler:
    """Transpiles EPL AST to JavaScript source code."""

    _TEMPLATE_RE = re.compile(r'\$\{([^}]+)\}|\$([a-zA-Z_][a-zA-Z0-9_]*)')

    def __init__(self, target='browser', module_format='esm'):
        """
        target: 'browser' or 'node'
        module_format: 'esm' (default) or 'cjs' (CommonJS)
        """
        self.target = target
        self.module_format = module_format
        self.indent = 0
        self.output = []
        self.in_class = None
        self.in_async = False  # True when inside async function
        self.class_properties = set()  # Property names of current class
        self.user_functions = set()
        self.async_functions = set()  # Track which functions are async
        self.esm_imports = set()  # ESM import specifiers
        self.requires = set()  # Node.js require() modules (CJS fallback)
        self.imports = []  # EPL import statements collected
        self.exported_names = set()  # Names to export

    def transpile(self, program: ast.Program) -> str:
        self.output = []
        self.user_functions = set()
        self.async_functions = set()
        self.requires = set()
        self.imports = []
        # Pre-scan for user-defined function names and async functions
        for stmt in program.statements:
            if isinstance(stmt, ast.FunctionDef):
                self.user_functions.add(stmt.name)
            elif isinstance(stmt, ast.AsyncFunctionDef):
                self.user_functions.add(stmt.name)
                self.async_functions.add(stmt.name)
        # Emit body
        body_lines = []
        for stmt in program.statements:
            self._emit_stmt(stmt)
        # Build final output with header
        header = []
        if self.target == 'node':
            header.append('// Generated by EPL Compiler v3.0 (Node.js target)')
            if self.module_format == 'esm':
                header.append('')
                for mod in sorted(self.esm_imports | self.requires):
                    header.append(f'import * as {mod} from "node:{mod}";')
            else:
                header.append('"use strict";')
                header.append('')
                for mod in sorted(self.requires):
                    header.append(f'const {mod} = require("{mod}");')
            if self.requires or self.esm_imports:
                header.append('')
        else:
            header.append('// Generated by EPL Compiler v3.0 (Browser target)')
            header.append('')
        footer = []
        if self.exported_names and self.module_format == 'esm':
            export_list = ', '.join(sorted(self.exported_names))
            footer.append('')
            footer.append(f'export {{ {export_list} }};')
        return '\n'.join(header + self.output + footer)

    def _line(self, text):
        self.output.append('  ' * self.indent + text)

    # ─── Statement Dispatch ─────────────────────────────

    def _emit_stmt(self, node):
        if node is None:
            return
        if isinstance(node, ast.VarDeclaration):
            self._emit_var_decl(node)
        elif isinstance(node, ast.VarAssignment):
            self._emit_var_assign(node)
        elif isinstance(node, ast.PrintStatement):
            self._emit_print(node)
        elif isinstance(node, ast.InputStatement):
            self._emit_input(node)
        elif isinstance(node, ast.IfStatement):
            self._emit_if(node)
        elif isinstance(node, ast.WhileLoop):
            self._emit_while(node)
        elif isinstance(node, ast.RepeatLoop):
            self._emit_repeat(node)
        elif isinstance(node, ast.ForRange):
            self._emit_for_range(node)
        elif isinstance(node, ast.ForEachLoop):
            self._emit_for_each(node)
        elif isinstance(node, ast.AsyncFunctionDef):
            self._emit_async_function(node)
        elif isinstance(node, ast.FunctionDef):
            self._emit_function(node)
        elif isinstance(node, ast.FunctionCall):
            self._line(f'{self._expr(node)};')
        elif isinstance(node, ast.ReturnStatement):
            self._emit_return(node)
        elif isinstance(node, ast.BreakStatement):
            self._line('break;')
        elif isinstance(node, ast.ContinueStatement):
            self._line('continue;')
        elif isinstance(node, ast.ClassDef):
            self._emit_class(node)
        elif isinstance(node, ast.MatchStatement):
            self._emit_match(node)
        elif isinstance(node, ast.TryCatch):
            self._emit_try_catch(node)
        elif isinstance(node, ast.MethodCall):
            self._line(f'{self._expr(node)};')
        elif isinstance(node, ast.PropertySet):
            self._emit_prop_set(node)
        elif isinstance(node, ast.IndexSet):
            self._emit_index_set(node)
        elif isinstance(node, ast.AugmentedAssignment):
            self._emit_aug_assign(node)
        elif isinstance(node, ast.ThrowStatement):
            self._emit_throw(node)
        elif isinstance(node, ast.FileWrite):
            self._emit_file_write(node)
        elif isinstance(node, ast.FileAppend):
            self._emit_file_append(node)
        elif isinstance(node, ast.ConstDeclaration):
            self._emit_const(node)
        elif isinstance(node, ast.AssertStatement):
            self._emit_assert(node)
        elif isinstance(node, ast.ExitStatement):
            self._emit_exit(node)
        elif isinstance(node, ast.WaitStatement):
            self._emit_wait(node)
        elif isinstance(node, ast.EnumDef):
            self._emit_enum(node)
        elif isinstance(node, ast.ImportStatement):
            self._emit_import(node)
        elif isinstance(node, ast.SuperCall):
            self._emit_super_call(node)
        # v4 AST node support
        elif isinstance(node, ast.InterfaceDefNode):
            self._emit_interface(node)
        elif isinstance(node, ast.ModuleDef):
            self._emit_module(node)
        elif isinstance(node, ast.TryCatchFinally):
            self._emit_try_catch_finally(node)
        elif isinstance(node, ast.ExportStatement):
            self._emit_export(node)
        elif isinstance(node, ast.VisibilityModifier):
            self._emit_stmt(node.statement)
        elif isinstance(node, ast.StaticMethodDef):
            self._emit_static_method(node)
        elif isinstance(node, ast.AbstractMethodDef):
            pass  # abstract methods are interface-only
        elif isinstance(node, ast.YieldStatement):
            self._emit_yield(node)
        elif isinstance(node, ast.DestructureAssignment):
            self._emit_destructure(node)
        elif isinstance(node, ast.ModuleAccess):
            self._line(f'{self._expr(node)};')
        else:
            import sys

            print(
                f'Warning: JS transpiler skipping unsupported statement: {type(node).__name__}',
                file=sys.stderr,
            )
            self._line(f'/* unsupported: {type(node).__name__} */')

    # ─── Statements ─────────────────────────────────────

    def _emit_var_decl(self, node):
        self._line(f'let {node.name} = {self._expr(node.value)};')

    def _emit_var_assign(self, node):
        if self.in_class and node.name in self.class_properties:
            self._line(f'this.{node.name} = {self._expr(node.value)};')
        else:
            self._line(f'{node.name} = {self._expr(node.value)};')

    def _emit_print(self, node):
        self._line(f'console.log({self._expr(node.expression)});')

    def _emit_input(self, node):
        if self.target == 'node':
            self.requires.add('readline')
            prompt_expr = self._expr(node.prompt) if node.prompt else '""'
            self._line('{')
            self.indent += 1
            self._line(
                'const _rl = readline.createInterface({ input: process.stdin, output: process.stdout });'
            )
            self._line(
                f'let {node.variable_name} = await new Promise(resolve => _rl.question({prompt_expr}, ans => {{ _rl.close(); resolve(ans); }}));'
            )
            self.indent -= 1
            self._line('}')
        else:
            if node.prompt:
                self._line(f'let {node.variable_name} = prompt({self._expr(node.prompt)});')
            else:
                self._line(f'let {node.variable_name} = prompt("");')

    def _emit_if(self, node):
        self._line(f'if ({self._expr(node.condition)}) {{')
        self.indent += 1
        for s in node.then_body:
            self._emit_stmt(s)
        self.indent -= 1
        if node.else_body:
            self._line('} else {')
            self.indent += 1
            for s in node.else_body:
                self._emit_stmt(s)
            self.indent -= 1
        self._line('}')

    def _emit_while(self, node):
        self._line(f'while ({self._expr(node.condition)}) {{')
        self.indent += 1
        for s in node.body:
            self._emit_stmt(s)
        self.indent -= 1
        self._line('}')

    def _emit_repeat(self, node):
        # Use unique loop counter to prevent collisions in nested repeats
        if not hasattr(self, '_repeat_counter'):
            self._repeat_counter = 0
        var = f'_i{self._repeat_counter}'
        self._repeat_counter += 1
        self._line(f'for (let {var} = 0; {var} < {self._expr(node.count)}; {var}++) {{')
        self.indent += 1
        for s in node.body:
            self._emit_stmt(s)
        self.indent -= 1
        self._line('}')

    def _emit_for_range(self, node):
        start = self._expr(node.start)
        end = self._expr(node.end)
        step = self._expr(node.step) if node.step else None
        if step:
            # Detect negative step for correct comparison operator
            try:
                step_val = int(step)
                cmp = '>=' if step_val < 0 else '<='
            except (ValueError, TypeError):
                # Dynamic step: use runtime direction check
                cmp = f'({step} > 0 ? {node.var_name} <= {end} : {node.var_name} >= {end})'
                self._line(
                    f'for (let {node.var_name} = {start}; {cmp}; {node.var_name} += {step}) {{'
                )
                self.indent += 1
                for s in node.body:
                    self._emit_stmt(s)
                self.indent -= 1
                self._line('}')
                return
            self._line(
                f'for (let {node.var_name} = {start}; {node.var_name} {cmp} {end}; {node.var_name} += {step}) {{'
            )
        else:
            self._line(
                f'for (let {node.var_name} = {start}; {node.var_name} <= {end}; {node.var_name} += 1) {{'
            )
        self.indent += 1
        for s in node.body:
            self._emit_stmt(s)
        self.indent -= 1
        self._line('}')

    def _emit_for_each(self, node):
        self._line(f'for (let {node.var_name} of {self._expr(node.iterable)}) {{')
        self.indent += 1
        for s in node.body:
            self._emit_stmt(s)
        self.indent -= 1
        self._line('}')

    def _emit_function(self, node):
        params = ', '.join(self._format_param(p) for p in node.params)
        # Check if function body contains yield statements → emit generator
        is_gen = self._contains_yield(node.body)
        prefix = 'function* ' if is_gen else 'function '
        self._line(f'{prefix}{node.name}({params}) {{')
        self.indent += 1
        for s in node.body:
            self._emit_stmt(s)
        self.indent -= 1
        self._line('}')

    def _contains_yield(self, stmts):
        """Check if any statement in the list contains a yield."""
        for s in stmts:
            if isinstance(s, ast.YieldStatement):
                return True
            for attr in ('body', 'then_body', 'else_body', 'try_body', 'catch_body'):
                nested = getattr(s, attr, None)
                if nested and isinstance(nested, list) and self._contains_yield(nested):
                    return True
        return False

    def _emit_async_function(self, node):
        """Emit async function with proper async keyword."""
        params = ', '.join(self._format_param(p) for p in node.params)
        self._line(f'async function {node.name}({params}) {{')
        self.indent += 1
        prev_async = self.in_async
        self.in_async = True
        for s in node.body:
            self._emit_stmt(s)
        self.in_async = prev_async
        self.indent -= 1
        self._line('}')

    def _emit_super_call(self, node):
        """Emit super(...) or super.method(...) call."""
        args = ', '.join(self._expr(a) for a in node.arguments)
        if node.method_name:
            self._line(f'super.{node.method_name}({args});')
        else:
            self._line(f'super({args});')

    def _format_param(self, p):
        """Format a parameter tuple (name, type, default) to JS."""
        name = p[0] if isinstance(p, (list, tuple)) else p
        default = p[2] if isinstance(p, (list, tuple)) and len(p) > 2 and p[2] is not None else None
        if default is not None:
            return f'{name} = {self._expr(default)}'
        return name

    def _emit_return(self, node):
        if node.value:
            self._line(f'return {self._expr(node.value)};')
        else:
            self._line('return;')

    def _emit_class(self, node):
        parent = f' extends {node.parent}' if node.parent else ''
        self._line(f'class {node.name}{parent} {{')
        self.indent += 1
        # Separate properties, init method, and other methods
        props = [
            (item.name, item.value) for item in node.body if isinstance(item, ast.VarDeclaration)
        ]
        methods = [
            item for item in node.body if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))
        ]
        init_method = None
        other_methods = []
        for m in methods:
            if m.name == 'init':
                init_method = m
            else:
                other_methods.append(m)
        # Track class property names for this. prefix resolution
        self.class_properties = {pn for pn, _ in props}
        # Also add any properties assigned in init body
        if init_method:
            for s in init_method.body:
                if isinstance(s, ast.VarAssignment):
                    self.class_properties.add(s.name)
                elif isinstance(s, ast.VarDeclaration):
                    self.class_properties.add(s.name)
        # Emit constructor: merge properties + init method
        if init_method:
            params = ', '.join(self._format_param(p) for p in init_method.params)
            self._line(f'constructor({params}) {{')
        else:
            self._line('constructor() {')
        self.indent += 1
        # Only auto-insert super() if parent exists AND init body doesn't have its own super call
        if node.parent and not init_method:
            self._line('super();')
        elif node.parent and init_method:
            has_super = any(isinstance(s, ast.SuperCall) for s in init_method.body)
            if not has_super:
                self._line('super();')
        for pn, pv in props:
            self._line(f'this.{pn} = {self._expr(pv)};')
        if init_method:
            self.in_class = node.name
            for s in init_method.body:
                self._emit_stmt(s)
            self.in_class = None
        self.indent -= 1
        self._line('}')
        # Emit other methods
        for m in other_methods:
            is_async = isinstance(m, ast.AsyncFunctionDef)
            params = ', '.join(self._format_param(p) for p in m.params)
            prefix = 'async ' if is_async else ''
            self._line(f'{prefix}{m.name}({params}) {{')
            self.indent += 1
            self.in_class = node.name
            prev_async = self.in_async
            if is_async:
                self.in_async = True
            for s in m.body:
                self._emit_stmt(s)
            self.in_async = prev_async
            self.in_class = None
            self.indent -= 1
            self._line('}')
        self.indent -= 1
        self._line('}')
        self.class_properties = set()  # Clear class context

    def _emit_match(self, node):
        self._line(f'switch ({self._expr(node.expression)}) {{')
        self.indent += 1
        for clause in node.when_clauses:
            for v in clause.values:
                self._line(f'case {self._expr(v)}:')
            self.indent += 1
            for s in clause.body:
                self._emit_stmt(s)
            self._line('break;')
            self.indent -= 1
        if node.default_body:
            self._line('default:')
            self.indent += 1
            for s in node.default_body:
                self._emit_stmt(s)
            self.indent -= 1
        self.indent -= 1
        self._line('}')

    def _emit_try_catch(self, node):
        self._line('try {')
        self.indent += 1
        for s in node.try_body:
            self._emit_stmt(s)
        self.indent -= 1
        vn = node.error_var or '_err'
        self._line(f'}} catch ({vn}) {{')
        self.indent += 1
        for s in node.catch_body:
            self._emit_stmt(s)
        self.indent -= 1
        if hasattr(node, 'finally_body') and node.finally_body:
            self._line('} finally {')
            self.indent += 1
            for s in node.finally_body:
                self._emit_stmt(s)
            self.indent -= 1
        self._line('}')

    # ─── v4 Statements ──────────────────────────────────

    def _emit_interface(self, node):
        """Emit interface as a JSDoc comment + empty class (structural typing in JS)."""
        self._line('/** @interface */')
        self._line(f'class {node.name} {{')
        self.indent += 1
        for sig in node.methods:
            if isinstance(sig, (list, tuple)):
                name = sig[0]
                params_list = sig[1] if len(sig) > 1 else []
            else:
                name = sig.get('name', 'unknown')
                params_list = sig.get('params', [])
            params = ', '.join(
                p[0] if isinstance(p, (list, tuple)) else str(p) for p in params_list
            )
            self._line(f'{name}({params}) {{ throw new Error("Not implemented"); }}')
        self.indent -= 1
        self._line('}')

    def _emit_module(self, node):
        """Emit module as an IIFE-based namespace or ES module object."""
        self._line(f'const {node.name} = (() => {{')
        self.indent += 1
        # Collect exported names
        exports = list(node.exports) if node.exports else []
        for s in node.body:
            if isinstance(s, ast.ExportStatement):
                # ExportStatement only has .name — record it
                exports.append(s.name)
            else:
                self._emit_stmt(s)
                if isinstance(s, ast.FunctionDef):
                    exports.append(s.name)
                elif isinstance(s, ast.VarDeclaration):
                    exports.append(s.name)
        export_obj = ', '.join(dict.fromkeys(exports))  # dedupe, preserve order
        self._line(f'return {{ {export_obj} }};')
        self.indent -= 1
        self._line('})();')

    def _emit_try_catch_finally(self, node):
        self._line('try {')
        self.indent += 1
        for s in node.try_body:
            self._emit_stmt(s)
        self.indent -= 1
        for clause in node.catch_clauses:
            # clause is (error_type, error_var, body) tuple
            err_type, var_name, body = clause[0], clause[1], clause[2]
            var_name = var_name or '_err'
            self._line(f'}} catch ({var_name}) {{')
            self.indent += 1
            if err_type:
                safe_err_type = (
                    err_type.replace('\\', '\\\\')
                    .replace('"', '\\"')
                    .replace('\n', '\\n')
                    .replace('\r', '\\r')
                )
                self._line(
                    f'if (!({var_name} instanceof Error) || !{var_name}.message.includes("{safe_err_type}")) throw {var_name};'
                )
            for s in body:
                self._emit_stmt(s)
            self.indent -= 1
        if not node.catch_clauses:
            self._line('} catch (_err) {')
            self.indent += 1
            self._line('/* no catch body */')
            self.indent -= 1
        if node.finally_body:
            self._line('} finally {')
            self.indent += 1
            for s in node.finally_body:
                self._emit_stmt(s)
            self.indent -= 1
        self._line('}')

    def _emit_export(self, node):
        # ExportStatement only has .name — record it for ESM export footer
        self.exported_names.add(node.name)

    def _emit_static_method(self, node):
        params = ', '.join(self._format_param(p) for p in node.params)
        self._line(f'static {node.name}({params}) {{')
        self.indent += 1
        for s in node.body:
            self._emit_stmt(s)
        self.indent -= 1
        self._line('}')

    def _emit_yield(self, node):
        self._line(f'yield {self._expr(node.value)};')

    def _emit_destructure(self, node):
        names = ', '.join(node.names)
        self._line(f'const [{names}] = {self._expr(node.value)};')

    def _emit_prop_set(self, node):
        self._line(f'{self._expr(node.obj)}.{node.property_name} = {self._expr(node.value)};')

    def _emit_index_set(self, node):
        self._line(f'{self._expr(node.obj)}[{self._expr(node.index)}] = {self._expr(node.value)};')

    def _emit_aug_assign(self, node):
        if self.in_class and node.name in self.class_properties:
            self._line(f'this.{node.name} {node.operator} {self._expr(node.value)};')
        else:
            self._line(f'{node.name} {node.operator} {self._expr(node.value)};')

    def _emit_throw(self, node):
        self._line(f'throw new Error({self._expr(node.expression)});')

    def _emit_file_write(self, node):
        if self.target == 'node':
            if self.module_format == 'esm':
                self.esm_imports.add('fs')
            else:
                self.requires.add('fs')
            self._line(
                f'fs.writeFileSync({self._expr(node.filepath)}, {self._expr(node.content)});'
            )
        else:
            self._line('console.warn("File I/O not available in browser");')

    def _emit_file_append(self, node):
        if self.target == 'node':
            if self.module_format == 'esm':
                self.esm_imports.add('fs')
            else:
                self.requires.add('fs')
            self._line(
                f'fs.appendFileSync({self._expr(node.filepath)}, {self._expr(node.content)} + "\\n");'
            )
        else:
            self._line('console.warn("File I/O not available in browser");')

    def _emit_const(self, node):
        self._line(f'const {node.name} = {self._expr(node.value)};')

    def _emit_assert(self, node):
        self._line(f'console.assert({self._expr(node.expression)}, "Assertion failed");')

    def _emit_exit(self, node):
        if self.target == 'node':
            self._line('process.exit(0);')
        else:
            self._line('throw new Error("EPL: Program exited");')

    def _emit_wait(self, node):
        if self.in_async:
            self._line(
                f'await new Promise(r => setTimeout(r, {self._expr(node.duration)} * 1000));'
            )
        else:
            # In non-async context, use setTimeout wrapper (await is illegal)
            self._line(
                f'setTimeout(() => {{ /* wait {self._expr(node.duration)}s */ }}, {self._expr(node.duration)} * 1000);'
            )

    def _emit_enum(self, node):
        self._line(f'const {node.name} = Object.freeze({{')
        self.indent += 1
        for i, m in enumerate(node.members):
            self._line(f'{m}: {i},')
        self.indent -= 1
        self._line('});')

    def _emit_import(self, node):
        filepath = node.filepath
        # Strip .epl extension for JS module name
        mod_name = (
            filepath.replace('.epl', '')
            .replace('/', '_')
            .replace('\\', '_')
            .replace('\\\\', '_')
            .replace('.', '_')
            .replace('-', '_')
        )
        if mod_name and mod_name[0].isdigit():
            mod_name = '_' + mod_name
        js_path = './' + filepath.replace('.epl', '.js')
        if self.module_format == 'esm' or self.target == 'browser':
            self._line(f'import * as {mod_name} from "{js_path}";')
        else:
            self._line(f'const {mod_name} = require("{js_path}");')

    # ─── Expression Rendering ───────────────────────────

    def _expr(self, node) -> str:
        if node is None:
            return 'null'
        if isinstance(node, ast.Literal):
            return self._expr_literal(node)
        if isinstance(node, ast.Identifier):
            if self.in_class and node.name in self.class_properties:
                return f'this.{node.name}'
            return node.name
        if isinstance(node, ast.BinaryOp):
            return self._expr_binary(node)
        if isinstance(node, ast.UnaryOp):
            return self._expr_unary(node)
        if isinstance(node, ast.FunctionCall):
            return self._expr_call(node)
        if isinstance(node, ast.PropertyAccess):
            return f'{self._expr(node.obj)}.{node.property_name}'
        if isinstance(node, ast.MethodCall):
            return self._expr_method(node)
        if isinstance(node, ast.IndexAccess):
            return f'{self._expr(node.obj)}[{self._expr(node.index)}]'
        if isinstance(node, ast.SliceAccess):
            return self._expr_slice(node)
        if isinstance(node, ast.ListLiteral):
            return f'[{", ".join(self._expr(e) for e in node.elements)}]'
        if isinstance(node, ast.DictLiteral):
            return self._expr_dict(node)
        if isinstance(node, ast.NewInstance):
            return f'new {node.class_name}({", ".join(self._expr(a) for a in node.arguments)})'
        if isinstance(node, ast.LambdaExpression):
            return f'({", ".join(p[0] if isinstance(p, (list, tuple)) else p for p in node.params)}) => {self._expr(node.body)}'
        if isinstance(node, ast.TernaryExpression):
            return f'({self._expr(node.condition)} ? {self._expr(node.true_expr)} : {self._expr(node.false_expr)})'
        if isinstance(node, ast.AwaitExpression):
            return f'await {self._expr(node.expression)}'
        if isinstance(node, ast.SuperCall):
            args = ', '.join(self._expr(a) for a in node.arguments)
            if node.method_name:
                return f'super.{node.method_name}({args})'
            return f'super({args})'
        if isinstance(node, ast.FileRead):
            if self.target == 'node':
                if self.module_format == 'esm':
                    self.esm_imports.add('fs')
                else:
                    self.requires.add('fs')
                return f'fs.readFileSync({self._expr(node.filepath)}, "utf-8")'
            return 'null /* File I/O not available in browser */'
        if isinstance(node, ast.ModuleAccess):
            return f'{node.module_name}.{node.member_name}'
        if isinstance(node, ast.SpreadExpression) if hasattr(ast, 'SpreadExpression') else False:
            return f'...{self._expr(node.expression)}'
        if isinstance(node, ast.ChainedComparison) if hasattr(ast, 'ChainedComparison') else False:
            parts = []
            for i in range(len(node.operators)):
                l = self._expr(node.operands[i])
                r = self._expr(node.operands[i + 1])
                op = node.operators[i]
                op_map = {'==': '===', '!=': '!=='}
                js_op = op_map.get(op, op)
                parts.append(f'({l} {js_op} {r})')
            return ' && '.join(parts)
        import sys

        print(
            f'Warning: JS transpiler skipping unsupported expression: {type(node).__name__}',
            file=sys.stderr,
        )
        return f'null /* unsupported expr: {type(node).__name__} */'

    def _expr_literal(self, node):
        if isinstance(node.value, bool):
            return 'true' if node.value else 'false'
        if isinstance(node.value, str):
            return self._js_string(node.value)
        if node.value is None:
            return 'null'
        return str(node.value)

    def _js_string(self, s):
        """Convert an EPL string to a JS string literal.
        If it contains $var or ${expr} interpolation, emit a JS template literal.
        Otherwise emit a properly escaped double-quoted string."""
        if self._TEMPLATE_RE.search(s):
            # Convert to JS template literal — EPL ${expr} / $var → JS ${expr} / ${var}
            # Escape backslashes first, then backticks to prevent injection
            escaped = s.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
            # Now re-introduce legitimate EPL interpolation
            # First handle ${expr} patterns from original string
            for m in self._TEMPLATE_RE.finditer(s):
                expr_braced = m.group(1)  # From ${expr}
                expr_bare = m.group(2)  # From $var
                if expr_braced:
                    old = '\\${' + expr_braced + '}'
                    new = '${' + expr_braced + '}'
                    escaped = escaped.replace(old, new, 1)
                elif expr_bare:
                    old = '$' + expr_bare
                    new = '${' + expr_bare + '}'
                    escaped = escaped.replace(old, new, 1)
            return f'`{escaped}`'
        # Regular string — escape special chars
        escaped = (
            s.replace('\\', '\\\\')
            .replace('"', '\\"')
            .replace('\n', '\\n')
            .replace('\r', '\\r')
            .replace('\t', '\\t')
        )
        return f'"{escaped}"'

    def _expr_binary(self, node):
        left = self._expr(node.left)
        right = self._expr(node.right)
        op = node.operator
        op_map = {
            'and': '&&',
            'or': '||',
            '==': '===',
            '!=': '!==',
            '**': '**',
            '//': 'Math.floor(/',
        }
        if op == '//':
            return f'Math.floor({left} / {right})'
        js_op = op_map.get(op, op)
        return f'({left} {js_op} {right})'

    def _expr_unary(self, node):
        if node.operator == 'not':
            return f'!{self._expr(node.operand)}'
        return f'{node.operator}{self._expr(node.operand)}'

    def _expr_call(self, node):
        args = ', '.join(self._expr(a) for a in node.arguments)
        # User-defined functions take priority over builtin mappings
        if node.name in self.user_functions:
            return f'{node.name}({args})'
        builtin_map = {
            'length': lambda: f'{self._expr(node.arguments[0])}.length' if node.arguments else '0',
            'to_integer': lambda: f'parseInt({args})',
            'to_text': lambda: f'String({args})',
            'to_decimal': lambda: f'parseFloat({args})',
            'uppercase': lambda: f'{self._expr(node.arguments[0])}.toUpperCase()',
            'lowercase': lambda: f'{self._expr(node.arguments[0])}.toLowerCase()',
            'type_of': lambda: f'typeof {args}',
            'absolute': lambda: f'Math.abs({args})',
            'round': lambda: f'Math.round({args})',
            'floor': lambda: f'Math.floor({args})',
            'ceil': lambda: f'Math.ceil({args})',
            'sqrt': lambda: f'Math.sqrt({args})',
            'power': lambda: f'Math.pow({args})',
            'max': lambda: f'Math.max({args})',
            'min': lambda: f'Math.min({args})',
            'log': lambda: f'Math.log({args})',
            'sin': lambda: f'Math.sin({args})',
            'cos': lambda: f'Math.cos({args})',
            'random': lambda: 'Math.random()',
            'sorted': lambda: (
                f'[...{self._expr(node.arguments[0])}].sort((a, b) => typeof a === "number" ? a - b : String(a).localeCompare(String(b)))'
            ),
            'reversed': lambda: f'[...{self._expr(node.arguments[0])}].reverse()',
            'range': lambda: self._js_range(node.arguments),
            'sum': lambda: f'{self._expr(node.arguments[0])}.reduce((a, b) => a + b, 0)',
            'char_code': lambda: f'{self._expr(node.arguments[0])}.charCodeAt(0)',
            'from_char_code': lambda: f'String.fromCharCode({args})',
            # Stdlib: DateTime
            'now': lambda: 'new Date().toISOString()',
            'today': lambda: 'new Date().toISOString().slice(0, 10)',
            'sleep': lambda: (
                f'await new Promise(r => setTimeout(r, {self._expr(node.arguments[0])} * 1000))'
                if self.in_async
                else '/* sync sleep not supported */ void 0'
            ),
            'year': lambda: f'new Date({self._expr(node.arguments[0])}).getFullYear()',
            'month': lambda: f'(new Date({self._expr(node.arguments[0])}).getMonth() + 1)',
            'day': lambda: f'new Date({self._expr(node.arguments[0])}).getDate()',
            'hour': lambda: f'new Date({self._expr(node.arguments[0])}).getHours()',
            'minute': lambda: f'new Date({self._expr(node.arguments[0])}).getMinutes()',
            'second': lambda: f'new Date({self._expr(node.arguments[0])}).getSeconds()',
            'day_of_week': lambda: f'new Date({self._expr(node.arguments[0])}).getDay()',
            # Stdlib: Crypto / encoding
            'uuid': lambda: 'crypto.randomUUID()',
            'uuid4': lambda: 'crypto.randomUUID()',
            'base64_encode': lambda: f'btoa({args})',
            'base64_decode': lambda: f'atob({args})',
            # Stdlib: Regex
            'regex_test': lambda: (
                f'new RegExp({self._expr(node.arguments[0])}).test({self._expr(node.arguments[1])})'
            ),
            'regex_match': lambda: (
                f'{self._expr(node.arguments[1])}.match(new RegExp({self._expr(node.arguments[0])}))'
            ),
            'regex_find_all': lambda: (
                f'[...{self._expr(node.arguments[1])}.matchAll(new RegExp({self._expr(node.arguments[0])}, "g"))]'
            ),
            'regex_replace': lambda: (
                f'{self._expr(node.arguments[2])}.replace(new RegExp({self._expr(node.arguments[0])}, "g"), {self._expr(node.arguments[1])})'
            ),
            'regex_split': lambda: (
                f'{self._expr(node.arguments[1])}.split(new RegExp({self._expr(node.arguments[0])}))'
            ),
            # Stdlib: Advanced Math
            'pi': lambda: 'Math.PI',
            'euler': lambda: 'Math.E',
            'atan': lambda: f'Math.atan({args})',
            'atan2': lambda: f'Math.atan2({args})',
            'asin': lambda: f'Math.asin({args})',
            'acos': lambda: f'Math.acos({args})',
            'tan': lambda: f'Math.tan({args})',
            'degrees': lambda: f'({self._expr(node.arguments[0])} * 180 / Math.PI)',
            'radians': lambda: f'({self._expr(node.arguments[0])} * Math.PI / 180)',
            'sign': lambda: f'Math.sign({args})',
            'clamp': lambda: (
                f'Math.max({self._expr(node.arguments[1])}, Math.min({self._expr(node.arguments[2])}, {self._expr(node.arguments[0])}))'
            ),
            'is_finite': lambda: f'Number.isFinite({args})',
            'is_nan': lambda: f'Number.isNaN({args})',
            'lerp': lambda: (
                f'({self._expr(node.arguments[0])} + ({self._expr(node.arguments[1])} - {self._expr(node.arguments[0])}) * {self._expr(node.arguments[2])})'
            ),
            # Stdlib: Collections
            'zip_lists': lambda: (
                f'{self._expr(node.arguments[0])}.map((v, i) => [v, {self._expr(node.arguments[1])}[i]])'
            ),
            'enumerate_list': lambda: f'{self._expr(node.arguments[0])}.map((v, i) => [i, v])',
            # Stdlib: OS / System
            'platform': lambda: (
                '(typeof process !== "undefined" ? process.platform : navigator.platform)'
            ),
            'args': lambda: '(typeof process !== "undefined" ? process.argv.slice(2) : [])',
            'env_get': lambda: f'(typeof process !== "undefined" ? process.env[{args}] || "" : "")',
            'print_error': lambda: f'console.error({args})',
            'exit_code': lambda: (
                f'process.exit({args})'
                if self.target == 'node'
                else f'(() => {{ throw new Error("EPL exit: " + {args}); }})()'
            ),
            # Stdlib: URL
            'url_encode': lambda: f'encodeURIComponent({args})',
            'url_decode': lambda: f'decodeURIComponent({args})',
            # Stdlib: Strings
            'format': lambda: self._js_format(node.arguments),
            # Stdlib: Networking (Node.js)
            'http_get': lambda: self._js_http_get(node.arguments),
            'http_post': lambda: self._js_http_post(node.arguments),
            'json_parse': lambda: f'JSON.parse({args})',
            'json_stringify': lambda: f'JSON.stringify({args})',
            # Stdlib: Timers
            'set_timeout': lambda: (
                f'setTimeout({self._expr(node.arguments[0])}, {self._expr(node.arguments[1])} * 1000)'
            ),
            'set_interval': lambda: (
                f'setInterval({self._expr(node.arguments[0])}, {self._expr(node.arguments[1])} * 1000)'
            ),
            'clear_timeout': lambda: f'clearTimeout({args})',
            'clear_interval': lambda: f'clearInterval({args})',
            # Stdlib: Type checking
            'is_number': lambda: f'(typeof {args} === "number")',
            'is_string': lambda: f'(typeof {args} === "string")',
            'is_list': lambda: f'Array.isArray({args})',
            'is_null': lambda: f'({args} === null || {args} === undefined)',
        }
        if node.name in builtin_map:
            return builtin_map[node.name]()
        return f'{node.name}({args})'

    def _js_format(self, arguments):
        """Generate JS for EPL format(template, ...args) → string interpolation."""
        if len(arguments) < 1:
            return '""'
        tmpl = self._expr(arguments[0])
        if len(arguments) == 1:
            return tmpl
        # Replace {} placeholders with template literal expressions
        parts = [self._expr(a) for a in arguments[1:]]
        # Use string replace chain
        result = tmpl
        for p in parts:
            result = f'{result}.replace("{{}}", String({p}))'
        return result

    def _js_http_get(self, arguments):
        """Generate JS fetch GET call."""
        url = self._expr(arguments[0])
        if self.in_async:
            return f'await fetch({url}).then(r => r.text())'
        return f'fetch({url}).then(r => r.text())'

    def _js_http_post(self, arguments):
        """Generate JS fetch POST call."""
        url = self._expr(arguments[0])
        body = self._expr(arguments[1]) if len(arguments) > 1 else '""'
        fetch_call = f'fetch({url}, {{method: "POST", headers: {{"Content-Type": "application/json"}}, body: JSON.stringify({body})}})'
        if self.in_async:
            return f'await {fetch_call}.then(r => r.text())'
        return f'{fetch_call}.then(r => r.text())'

    def _js_range(self, arguments):
        """Generate correct JS for range(n), range(start, end), range(start, end, step)."""
        if len(arguments) == 1:
            n = self._expr(arguments[0])
            return f'Array.from({{length: {n}}}, (_, i) => i)'
        elif len(arguments) == 2:
            start = self._expr(arguments[0])
            end = self._expr(arguments[1])
            return f'Array.from({{length: {end} - {start}}}, (_, i) => {start} + i)'
        elif len(arguments) >= 3:
            start = self._expr(arguments[0])
            end = self._expr(arguments[1])
            step = self._expr(arguments[2])
            return f'Array.from({{length: Math.ceil(({end} - {start}) / {step})}}, (_, i) => {start} + i * {step})'
        return '[]'

    def _expr_method(self, node):
        obj = self._expr(node.obj)
        args = ', '.join(self._expr(a) for a in node.arguments)
        method_map = {
            'add': 'push',
            'push': 'push',
            'remove': 'splice',
            'upper': 'toUpperCase',
            'uppercase': 'toUpperCase',
            'lower': 'toLowerCase',
            'lowercase': 'toLowerCase',
            'trim': 'trim',
            'contains': 'includes',
            'replace': 'replace',
            'starts_with': 'startsWith',
            'ends_with': 'endsWith',
            'split': 'split',
            'reverse': 'reverse',
            'sort': 'sort',
            'substring': 'substring',
            'index_of': 'indexOf',
            'join': 'join',
            'find': 'find',
            'repeat': 'repeat',
            'char_at': 'charAt',
            'to_list': 'split',
        }
        m = node.method_name
        if m == 'remove':
            return f'{obj}.splice({obj}.indexOf({args}), 1)'
        if m == 'length':
            return f'{obj}.length'
        if m == 'sort':
            # Use numeric-aware comparator
            return f'{obj}.sort((a, b) => typeof a === "number" ? a - b : String(a).localeCompare(String(b)))'
        js_m = method_map.get(m, m)
        return f'{obj}.{js_m}({args})'

    def _expr_slice(self, node):
        obj = self._expr(node.obj)
        start = self._expr(node.start) if node.start else '0'
        end = self._expr(node.end) if node.end else ''
        if end:
            return f'{obj}.slice({start}, {end})'
        return f'{obj}.slice({start})'

    def _expr_dict(self, node):
        parts = []
        for k, v in node.pairs:
            val = self._expr(v)
            # If key is a valid JS identifier, emit unquoted; otherwise quote it
            if isinstance(k, str) and re.match(r'^[a-zA-Z_$][a-zA-Z0-9_$]*$', k):
                parts.append(f'{k}: {val}')
            else:
                parts.append(f'{self._js_string(str(k)) if isinstance(k, str) else k}: {val}')
        joined = ', '.join(parts)
        return '{' + joined + '}'


def transpile_to_js(program: ast.Program) -> str:
    """Convenience function to transpile EPL AST to browser JavaScript."""
    return JSTranspiler(target='browser').transpile(program)


def transpile_to_node(program: ast.Program, module_format='esm') -> str:
    """Transpile EPL AST to Node.js JavaScript.
    module_format: 'esm' (default, import/export) or 'cjs' (CommonJS require)."""
    return JSTranspiler(target='node', module_format=module_format).transpile(program)
